### ISSUE TITLE
Ableton Live controls are too sensitive on Mac client

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#183]
**Imported issue:**
- Author: nick.bolton.uk (Google user)
- Date: 2009-08-26 00:00:00
- Legacy ID: 192

Using Windows Vista as the server, and Mac OS X 10.5.x as the client, run the  
Ableton Live 8 demo. When using the sliders, they behave a lot more sensitive  
than normal, making them practically unusable.

**Comment by SmileCafe** [comment]
I have the same issue. Have you found the solution?

**Comment by adrianpauly** [comment]
I'm having the exact same issue only with newer software. Windows 10, macOS Mojave and Ableton Live 10. Cursor movement is normal, but sensitivity goes through the roof the moment you start interacting with any draggable interface elements such as knobs and zoom controls.

**Comment by SmileCafe** [comment]
I bought Ableton live 9 suite pretty soon when it was released. I have been waiting for the fix for this issue. Nobody has been giving a shit about it for a long time. I'm still waiting for the fix. That's why I didn't buy the new software Ableton Live 10. There is strong possibility for you that's gonna happen to you as well when Ableton 11 is released. Then somebody will say like you "I have the same issue only with the newer software."
The thing is if this synergy developer won't give any interest in this matter we have pretty much no option at all. Nobody knows this little thing might blow away 1 gran easily.

**Comment by adrianpauly** [comment]
It's weird because it's such a specific issue. I haven't had this problem with any other app other than Ableton Live. I don't think that the devs don't care, it's probably not a priority since it's a very specific problem probably happening to only a handful of people. I'm wondering why this issue was closed, was anything resolved? Could you give us some insight, @nbolton ? Thanks!

**Comment by SmileCafe** [comment]
8 ignored, 9 ignored. Now the time for 10. Probably 11 the same. You know my conclusion? Apple is a piece of shit.

**Comment by nbolton** [comment]
> Could you give us some insight, @nbolton ? Thanks!

I've reopened the issue. Please let me know if you have any more info.

**Comment by SmileCafe** [comment]
Ableton 10 has the tablet mode. That fixes the issue. Thanks for the reopening, but a little late.

**Comment by adrianpauly** [comment]
I didn't know about the Pen Tablet mode, thanks @SmileCafe 

@nbolton, this won't be an issue anymore for anyone with the latest version of Ableton Live. Not sure if this is useful for you but here's Ableton's info regarding that feature https://help.ableton.com/hc/en-us/articles/209769585-Pen-Tablet-Mode-in-Live-10

**Comment by el-banan** [comment]
Pen tablet mode is not a fix, it's just a workaround. Ableton, without pen tablet mode, hides the mouse cursor and allows controlling faders, knobs and zoom levels with a mouse. Similairly to how full screen FPP games work. @nbolton is this something that Synergy can support?

**Comment by nbolton** [comment]
This issue has been inactive for a while so I'll close it. Please let me know if this is still an issue and I'll reopen it.
