### ISSUE TITLE
Right shift not received when client is running Remote Desktop

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#233]
**Imported issue:**
- Author: jeffmic34 (Google user)
- Date: 2009-10-02 00:00:00
- Legacy ID: 242

> Tips:  
> - Have you searched for an existing or similar issue?  
>   Yes - did not see this exact issue  
> - If you have a question, please post on the mailing list.  
> - Have you selected the correct issue template?  
>   Yes  
> 
> What list of steps will reproduce the problem?  
> Open a Remote Desktop session from XP to Windows 2000.  Attempt to use  
> Right shift key.  Does not work.  
> 
> What version of operating system, and Synergy+ are you using?  

Windows XP 64bit as server, windows XP x86 as client.  Using  
Synergy+1.3.4x64 on the XP 64bit server, and Synergy+1.3.4x86 on XP x86  
client.  

> What is the expected behaviour, and what happens instead?  
> Expect right shift key to function like left shift key when using Remote  
> Desktop.  Left shift key works fine, right shift key does not work.  
> 
> Is there a way of temporarily working around your problem?  
> Use the left shift-key when using Remote Desktop.  Unfortunately this  
> means retraining 30 years of typing behavior.

**Comment by markusobsidian** [comment]
Is there a solution to this? I still have this issue with 1.6.2. Issue seems to have been closed.

Thanks.

**Comment by markusobsidian** [comment]
Just updated to 1.7.3. Still an issue. Is there anything that we can do here?

**Comment by JonnyPhenomenon** [comment]
I recently started using RDP to connect to my work machines and I discovered this bug as well.  I was using 1.75 stable, I tried rolling back 1.71, and I am now running 1.8 beta.  the issue is consistent across all three versions.  

my synergy server is a windows 10 64bit system, my client is XP 32bit.  the two machines I am RDP'd into are a windows 2008 server and windows 10 64bit respectively.  I noticed when I launch the onscreen keyboard within my rdp session and watch it as I use my (synergy Servers) physical keyboard to send keys, the onscreen keyboard shows that I am pressing left or right shift correctly, however, while left shift works normally, the right shift appears to release the instant I press any other key I wish to modify. 

This seems to reflect wehat severn.tsui said oh, what, 6 years ago now?

Anyway, this makes me a sad panda :(

**Comment by JonnyPhenomenon** [comment]
I just discovered something new... If I RDP to a machine from my synergy client and start typing in notepad or whatever, and I press and hold the left shift key, then press the right shift key, and release the left shift key, then the right shift key works perfectly, that is, right up until I tap the left shift key even once, or if I mouse over to the synergy server screen...

**Comment by psychoticbeef** [comment]
Same for me. Debian Linux server, OSX 10.11.6 client, RDP from OSX to Windows. Shift does not work.

**Comment by tdbe** [comment]
STILL HAPPENING on Ubuntu 20.04.1 LTS, Windows 10 client.
If do like @JonnyPhenomenon, my keyboard never lets go of the shift even if I do let go. It then reverts if I press the left shift again.

**Comment by andreacndn** [comment]
@tdbe thank you for raising the issue again, we'll review the problem.

**Comment by nbolton** [comment]
This issue has been inactive for a while so I'll close it. Please let me know if this is still an issue and I'll reopen it.
