### ISSUE TITLE
High client CPU usage after being disconnected. CSocketMultiplexer null job buildup.

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#2866]
**Imported issue:**
- Author: Brian Vincent
- Date: 2011-08-11 23:19:43
- Legacy ID: 2935
- Version: 1.4.3

**Steps to reproduce:**  
1. Start up a synergy client that attempts to connect to a server that is refusing connections.  
2. Wait a day or longer.  
3. Connect to the client and move around the mouse.  

Expected: Normal smooth mouse movement with minimal CPU.  
Actual: Extremely laggy mouse movement and use a lot of CPU.  

Here is my assessment.  If you add a debug message to output the size of the list m_socketJobs inside of CSocketMultiplexer, you'll notice the list growing every second when it tries to connect to the server.  This is causing a memory leak and causing the CPU to rise every time it traverses the entire list with nextCursor.  

This appears to be the same bug as bug #65, but that was 2 years ago so maybe not. It certainly seems like the bug from this discussion:  
http://groups.google.com/group/synergy-plus/browse_thread/thread/b5ab3ff4c7449493  

Here is my patch to src/lib/net/CSocketMultiplexer.cpp that appears to fix it.  

--- CSocketMultiplexer.cpp.orig 2011-08-11 17:08:31.000000000 -0500  
+++ CSocketMultiplexer.cpp      2011-08-11 17:11:09.000000000 -0500  
`@ -255,6 +255,7 @`  
                for (CSocketJobMap::iterator i = m_socketJobMap.begin();  
                                                        i != m_socketJobMap.end();) {  
                        if (*(i->second) == NULL) {  
-                               m_socketJobs.erase(i->second);  
                              m_socketJobMap.erase(i++);  
                              m_update = true;  
                      }  

**Versions (Synergy, OS):**  

Server:  
Client 1: 1.4.3  

**Workaround:**  

Restart the client.

**Comment by jrconlin** [comment]
Not sure if this is fully related, but I'm observing a similar behavior with my current configuration:

Synergy:1.7.3 configured as Client
Host: Windows 8.1 Pro

Server seems not to matter. However if the network is not responding or unavailable, procexp will report that a thread will consume a LARGE amount of CPU, to the point where the fan starts kicking on an i7 with 8 cores. This is particularly noticeable when coming out of sleep. 

generally, stopping synergyd from the Services panel kills the CPU load. It definitely feels like a back-off timer is failing and something is falling into an infinite loop. I'm not seeing any strong memory leaks or other resource drains. 

It's been far too long since I've dug into C++, but I can try looking into the code to see if I can spot anything.

**Comment by XinyuHou** [comment]
Hi,

Please try our latest nightly for 1.7.4 release.

http://synergy-project.org/nightly?filter=44fa44f

Feedback welcome.

Thank you
Jerry

--
Xinyu Hou (Jerry)
Senior Software Engineer
<http://synergy-project.org/>

**Comment by jrconlin** [comment]
Installed, and am not seeing the same high CPU behavior. After initial query, threads go to near zero CPU, even with networking off. Well done!

**Comment by mihaibirsan** [comment]
I'm seeing the same behavior with 1.7.3. Is there a due date on 1.7.4, or should I install the nightly?

**Comment by XinyuHou** [comment]
Aleady fixed
