### ISSUE TITLE
Middle click does not close Chrome tab on Mac client

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#2975]
**Imported issue:**

* Author: Desmond Brand
* Date: 2011-12-27 00:11:33
* Legacy ID: 3044
* Version: 1.4.5

**Steps to reproduce:**  
  
1. Start Windows 7 64 bit Synergy 1.4.5 server  
2. Connect with OS X Lion Synergy 1.4.5 client  
3. Open Chrome 16.0.912.63  
4. Middle click a tab to close it  
  
Expected: Tab closes  
Actual: Tab does not close, middle click is ignored  
  
Note that middle clicking a link works - middle click only fails to work when closing a tab.  
  
**Versions (Synergy, OS):**  
  
Server: Windows 7 64 bit, Synergy 1.4.5  
Client 1: OS X Lion, Synergy 1.4.5  
  
**Comments:**  
  
See http://code.google.com/p/chromium/issues/detail?id=108607 for the same issue in the Chromium tracker

**Comment by dan-bennett** [comment]
*bump*

Still an issue on Windows 8.1 server / Mac OS X 10.9.5 client both running Synergy 1.6.2.

**Comment by Momodedf** [comment]
Hello,

Same issue for MacOS X 10.10.2 as client and Ubuntu 14.04 both using Synergy 1.6.2

**Comment by ho0ber** [comment]
Same issue with Windows 7 as server and OSX 10.9 as client, both using Synergy 1.6.2.

**Comment by samling** [comment]
+1, this is still an issue as of v1.7.4 stable. Mousewheel click will open tabs but not close them still. Using OS X 10.10 as a client and Windows 7 as a server.

**Comment by razamatan** [comment]
still an issue on 1.7.2 stable.  osx yosemite client and ubuntu 14.04 server.

**Comment by genesy** [comment]
+1 still an issue 1.7.2 yosemite on host and server.

**Comment by bwanagary** [comment]
+1, this is still an issue as of v1.7.4 stable. Mousewheel click will open tabs but not close them still. Using OS X 10.10.3 as a client and Windows 7 as a server.

**Comment by spronkey** [comment]
+1 this has been an issue for years and needs resolving. As does left click not working entirely correctly in certain circumstances (i.e. official twitter app).

**Comment by Pistos** [comment]
+1  Linux host, OSX client.

**Comment by mrfinks** [comment]
+1 Ubuntu 14.04 server, OSX 10.10.5 client
Chrome 45.0.2454.101

**Comment by szukai** [comment]
+1 Win7 host, OSX client

**Comment by zeebrah** [comment]
+1 Win8 host, OSX client.

This is my ONLY issue with synergy. GREAT software otherwise. Thanks!

**Comment by bunjiboys** [comment]
I just submitted a pull-request that should fix this. Basically this is down to mouse events not being correctly translated from Synergy to Mac. For other OS's left button is id 1, middle is 2 and right button is 3, however on Mac they have flipped right and middle buttons so middle button is 3 and right button is 2.

My pull-request correctly translates the incoming events so that button index as well as the actual mouse event are sent correctly the the OS.

Below is an example flow for a right click and a middle click before:

**Right Click**
1. User clicks right button
1. Synergy sends a button press event to the client of button id 3
1. OSX Client lookup the system event to send, in this case it would send the `kCGEventOtherMouseDown` event with a button id of the right mouse button
1. The OS would correctly handle the second button (right mouse button) being clicked

**Middle click**
1. User click middle button
1. Synergy send button press event to the client of button id 2
1. OSX Client lookup the system event to send, here it will send `kCGEventRightMouseDown` event with the button id of the middle button
1. Events don't match what they should be, and the click is incorrectly handled

I believe the reason for some applications correctly handling the middle click (ie. firefox) is because they might hook into a lower API for intercepting mouse clicks and look at the button passed to the API, but thats just a guess.

**Comment by bwanagary** [comment]
Thank you!

**Comment by ElijahLynn** [comment]
PR mentioned above by bunjiboys is https://github.com/synergy/synergy/pull/5072

**Comment by clangen** [comment]
Any updates here? The fix looks straight forward and has been confirmed by a couple users. Can we get this merged into the next release? I'd love to be able to use Synergy again after all these years.

**Comment by evanhabeeb** [comment]
Bump

**Comment by ElijahLynn** [comment]
@evanhabeeb Looks like it is working in latest nightly => https://github.com/symless/synergy/pull/5072#issuecomment-208266581

**Comment by evanhabeeb** [comment]
@ElijahLynn awesome! Thanks for pointing me in the right direction. Works great.

**Comment by XinyuHou** [comment]
Please test our nightly builds.
http://synergy-project.org/nightly?filter=synergy-pr5072_middle_click_fix-beta-c7dc5ff

**Comment by lhung** [comment]
Been running this build for a couple days now. Working great!

**Comment by GollyRojer** [comment]
Successful; middle button closes tab.
Synergy Version: 1.8.2-rc1-12e0120
Tested OS: win10

**Comment by LeadManPL** [comment]
Status of test: SUCCESS

Server:
Linux 4.4.0-33-generic #52-Ubuntu SMP Fri Jul 22 19:16:44 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
synergy-v1.8.2-rc1-12e0120-Linux-x86_64.deb

Client:
Windows 7 Professional SP 1
synergy-v1.8.2-rc1-12e0120-Windows-x64
