### ISSUE TITLE
Hash (#) key not working (UK keyboard, win7 server, mac client)

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#3127]
**Imported issue:**
- Author: Peter Choo
- Date: 2012-05-02 13:09:41
- Legacy ID: 3197

**Steps to reproduce:**  
1. Open TextEdit  
2. Press # key  

Expected: # symbol appears in text edit  
Actual: Something completely different:  

1.4.6: Command+3 combination sent instead  
1.4.7: Command+3 combination sent instead  
1.4.8: Numeric 3 sent instead  

Interestingly, on 1.4.8 if I press alt+# (option+# on the mac) I get the hash symbol.  Shift+# gives me the ~ symbol (expected behaviour).  

**Versions (Synergy, OS):**  

Server: 1.4.8 Windows 7 64-bit  
Client 1: 1.4.6-8 Mac OS X Lion 10.7.3  

**Workaround:**  

Downgrading to 1.3.8 client on the mac (with 1.4.8 server) has worked for me.    

Option+# gives me the # symbol in 1.4.8 and 1.4.7.  I didn't test this in 1.4.6.  

I am currently using 1.4.7 so that I can use the right shift, and click + drag.  

**Comments:**  

Although this has now once again disabled my ctrl+drag ability on the mac, which was the reason for the upgrade in the first place.

**Comment by Momodedf** [comment]
Hello,

Same issue for MacOS X 10.10.2 as client and Ubuntu 14.04 both using Synergy 1.6.2

**Comment by sbnmrk** [comment]
Hi,

same issue here with a Gentoo server and Mac OS X 10.10.2 as a client both running Synergy 1.6.2. Keyboard is an Apple Keyboard with german layout that works as expected on the server machine regarding the [#/'] key. On OS X you get [3/`] through Synergy when pressing the same key.

For a programmer the bug is pretty annoying since you need the hash/apostrophe key all the time ... :/

Thanks!

**Comment by tripplet** [comment]
Hi, same issue here, Windows 8.1 as server & OS X 10.10.2 as client both running synergy 1.6.2
German keyboard on windows PC.
I also have problems with other keys I need quite a lot for programming:
Pressing the following key's does not result in the desired characters 

Alt+5 expected [ got nothing 
Alt+6 expected ] got nothing
Alt+8 expected { got 5
Alt+9 expected } got 6
Shift+# expected ' got `

**Comment by SebastianAigner** [comment]
Same Issue, I use the German Keyboard Layout on a "Das Keyboard Professional". I guess this really is an issue with ISO/ANSI keyboard detection as @nbolton suggested.

**Comment by eljtel** [comment]
Are there any workarounds for this issue? 

The following characters are also not passed from Mac server to Windows client: §±€

**Comment by comes** [comment]
any solutions for this problem?

**Comment by adripol94** [comment]
same bug Mac os client and Ubuntu for server

Alt+5 expected [ got nothing 
Alt+6 expected ] got nothing
Alt+8 expected { got 5
Alt+9 expected } got 6
Shift+# expected ' got `

**Comment by joernv** [comment]
Same bug here with Windows 7 server and OS X 10.11 client using Synergy 1.8.0-alpha-19835b6 or 1.7.5-rc1 with a german keyboard. This is really annoying an makes Synergy kind of unusable for coding. Any hints for a workaround?

**Comment by benbooth493** [comment]
Same issue here.

Running server on MacBook Pro and client on Fedora 23.
I can't LeftAlt+3 or RightAlt+3 to generate '#' character.

**Comment by AskinOharis** [comment]
I am using Windows 10 as server and OS X El Capitan 10.11.2 as client and this is still a Bug in 1.8.1 beta! -> # on PC prints a 3 on MAC and so on ...

Before I updatet to Windows 10 I had Vista and I used old synergy versions, some thing like 1.3.1, on both machines -> ALL FINE

This bug, which seems to be reported also in some other issues, is dated back to 2014 on several plattforms. This is a show stopper, as you know for sure by yourself, but it seems that it doesn´t get the attention as it deserves.

**Comment by jaoord** [comment]
While you're there, please also fix #4

**Comment by qaisjp** [comment]
Pretty sure this is still an issue.

**Comment by qaisjp** [comment]
With Windows as the server and macOS as the client, my solution to this is to switch the macOS keyboard from "British" to "British - PC". I'm not sure if this is a proper fix though.

**Comment by connrs** [comment]
Hi folks,

I've come here from #2637 which was marked as a duplicate of this (despite this on being about Win host/Mac guest and 2637 is Mac host/Win guest).

Needless to say I need to report that Mac host/Win guest is still definitely an issue. I'm unable to send # (Alt+3) to a Windows 10 guest from a macOS host running 1.14 stable (or 1.13 or 1.12 for that matter).

However, I am able to do it in reverse. Win 10 host with a macOS client is working. Perhaps this is purely because I've got a UK keyboard layout with a # symbol available as a standard key with no modifiers needed.

macOS 11.4,  Host, 1.14 stable, Standard Mac UK keyboard layout on Magic Keyboard
Windows 10 Guest 1.14 stable, Standard UK keyboard layout on Microsoft Keyboard

**Comment by comes** [comment]
after a couple of years with no response, I switched to logitech flow (https://www.logitech.com/en-us/software/features/flow.html) which works pretty well for my

**Comment by nbolton** [comment]
This issue has been inactive for a while so I'll close it for now. 
Please let me know if this is still an issue so that I can reopen it.
