### ISSUE TITLE
Notepad++ reload message box causes client mouse to freeze

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#337]
**Imported issue:**
- Author: E3pOBOT (Google user)
- Date: 2010-01-17 00:00:00
- Legacy ID: 346

> What list of steps will reproduce the problem?  
> While running in a normal state with the ability to move mouse to other  
> computer monitors, have your mouse on another screen and edit a file in an  
> external editor, while the file is also loaded in notepad++. This will  
> cause notepad++(on the host or server machine) to load up a "blah" has been  
> modified dialog box. This will then lock the mouse on all screens and make  
> it impossible to get out without restarting the computer, or CONTROL ALT  
> DEL\SWITCH USER and then logging back in, and killing synergy in task manager.  
> 
> What version of operating system, and Synergy+ are you using?  
> The latest beta build in the download section  
> 
> Is there a way of temporarily working around your problem?  
> Control alt del, switch user, log back in, kill synergy in task  
> manager(right click on task bar and click task manager, not control alt del  
> task manager)  
> 
> Would you like to solve the problem yourself and submit a patch?  
> I wish i could!

**Comment by paponius** [comment]
Similar issue here, except it will freeze only Notepad++ which has to be then killed.
Also happens right after a message about a file change is shown.
I don't have two monitors and it only happens if I click INSIDE the Notepad++ with a PEN or a finger, which are two separate pointing devices. If I use touchpad, touchstick or a mouse, problem will not arise.
And if I click on taskbar using pen or finger to get focus to the Notepad++, It works OK and will not freeze.

Could this be the same problem?

**Comment by XinyuHou** [comment]
Close as an obsolete issue

**Comment by paponius** [comment]
ok, not sure if fixed with Synergy, current version of Notepad++ doesn't have this bug, which in turn will not cause the rest of the issue. Not sure if an issue in another program can't do this again.
