### ISSUE TITLE
Choice of IP address

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#3566]
**Imported issue:**
- Author: Martin Wilkins
- Date: 2013-06-12 10:26:37
- Legacy ID: 3636

**Steps to reproduce:**

Server is setup on my non desired IP addresss. I want the IP address to be my main IP address (172.16.90.61) not 192.168.0.122 which is my secondary IP address

Expected: Offer a choice of IP address

Actual: TODO

**Versions and operating systems:**

**Comment by mindcreations** [comment]
Why have you closed this? I think it will be a really useful config item. I've VPN connections from my desktop and often Synergy takes the IP of the VPN instead of the local static LAN ip address.

The bad effects of taking VPN address are:
1) I've to connect the other computer on the same VPN to make them talk via Synergy
2) If I disconnect a VPN Synergy stops communicating with the other computer (see point 1)

Let a human take the decision of which IP Synergy has to use! Default configuration can have auto-config enabled, of course.

**Comment by oscarmolinadev** [comment]
In my job have same problems with VPN.

PC1 MAIN: Run Synergy Server 
PC2 Notebook: Run Client

All PCs connected with LAN/WAN network, local ip, and works correctly.

PROBLEM:

PC1 also conected with a VPN, sometimes lost connection with Synergy. In GUI I have seen that the server IP has changed by the VPN. If turn off VPN and reboot Synegry work again.

**Comment by XinyuHou** [comment]
you can specify which network adapter to use in settings->interface
