### ISSUE TITLE
Keys will randomly be repeated at length on client

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#375]
**Imported issue:**
- Author: Shiy...@gmail.com (Google user)
- Date: 2010-02-19 00:00:00
- Legacy ID: 384

> IMPORTANT: Please research your problem thoroughly before opening  
> a new ticket. The following tips are provided to help you.  
> 
> What list of steps will reproduce the problem?  

Doesn't happen predictably, don't know how to reproduce.  

> What version of operating system, and Synergy+ are you using?  

Server is running XP Home Edition, client is running Ubuntu 9.04. Synergy+  
is 1.3.4.  

> What is the expected behaviour, and what happens instead?  

Occasionally a key that I've only struck once is repeated many times -  
anything from five to thirty.  

> Is there a way of temporarily working around your problem?  

Well, I can delete the extra characters entered.  

> Would you like to solve the problem yourself and submit a patch?  

I can't code, so.

**Comment by BrianHoldsworth** [comment]
summary - this comment is all lower-case because i reverted to synergyc 1.3.1 to fix the repeating keys problems, and now the shify-key modifier is ignored.

longer version - i am running latest synergys on morphos as my server, and client is current ubuntu 15.10. i experienced the repeating keys issue with the standard ubuntu synergyc version 1.6.2. i then built binaries and found the problem was still present in latest code from github, and old version 1.4.1, and old version 1.3.6. i then went all the way back to 1.3.1 because i have that version running on a mac client and there is not repeating keys problem. with some serious consternation, i was able to build 1.3.1 on ubuntu 15.10 and see now that it also does not suffer from the repeating keys. however, the shift key is not recognized.

throughout my testing, the easiest way to recreate the repeating keys issue was to simply open an xterm on the client and type a command, followed by return. after a short pause, i would always get a long repeating stream of returns in the xterm console. it stops as soon as you press some other key.

i would say this bug was introduced in between 1.3.1 and 1.3.6 and is still present in the latest source code from github.

**Comment by kent-larsson** [comment]
I have this problem as well. It's nothing special with my network. It's a normal wireless network with some lag. This shouldn't happen... Sigh.. Are you guys looking at it?

**Comment by mxyzplx** [comment]
Is this still an issue that's being considered? I've been experiencing it... seems like forever now. Have an Ubuntu 16.10 server, wired, and an Ubuntu 16.10 client, wireless (although it makes no difference if it's wireless or wired). This has been an issue with the stock version of synergy available in the Ubuntu repositories (1.6.2), and the latest available version (1.8.7), and seems to have been an issue for as long as I can remember. 

I've tried lowering the MTU on both machines; creating a QoS rule in the router for the application; forwarding the port on the router and in the firewalls; and I ticked "Check clients every 5000 ms" simply because I didn't see what that does in the wiki, and wanted to see if it would make a difference.

So far nothing seems to make a difference, and iiiits gettttttttttttting very irrrrrrrrrrrrrritating havvvvvvvvvvving to delllllllllllete soooooooooo many lettttttttttters alllllllll the timmmmmmmmme.

**Comment by XinyuHou** [comment]
Close as an obsolete issue

**Comment by hmcclungiii** [comment]
How is this issue closed?
Server: Windows 10
Client: Ubuntu 16.04

**Comment by 5AMsan** [comment]
Same issue.
Server: Windows 10
Client: Ubuntu 16.04

**Comment by wbarksdale** [comment]
Same issue Mac OSX 10.15.6 and Ubuntu 16.04 LTS. Mac OS is the host.

**Comment by hcaiano** [comment]
Same issue on Windows 10 on both client and host.

**Comment by AJChapman** [comment]
Same issue, on a home wifi network, client and server both running NixOS (Linux), Synergy version 1.11.1. It's a very frustrating experience, as you can still get things done, but you're continuously undoing the mistakes the keyboard forces you to make.

Note that on both server and client I have a high key repeat rate set, using `xset r rate 200 100`. Could this be contributing to how often I see the issue? If so then it could help for reproducing the bug.

**Comment by andreacndn** [comment]
@AJChapman could you please confirm if you experience the same error on 1.12.0?

Thanks,
Andrea
VP of Technology @ Symless

**Comment by justinaquino** [comment]
experiencing the same. 
ubuntu 20.04.1 only on Client System. 
Google Wifi
Synergy 1.12.2 Build date Nov 12 2020. 
I end up only writing at length in the Server Computer (opening the Gdoc in this computer).

**Comment by klieret** [comment]
I also see this issue with 1.14.0-stable-67d824b8 built June 8 2021 on ubuntu 19.10 

This isn't only frustrating but downright dangerous, especially when writing in the command line.

**Comment by klieret** [comment]
It's probably best to disable key repeat (i.e. that a key is repeated after a key is pressed for x ms) while this is an issue. An easy way to do so on Ubuntu with gnome is `Settings` > `Universal Access` > disable `Repeat Keys`

**Comment by allanwmacdonald** [comment]
I just had this happen with Win10 server and Ubuntu 20.04 LTS Client: When I hit the screen lock key sequence on the client, (winkey-L), both the client and server lock at the same time because the windows server picks up the key sequence regardless of mouse focus.  The result: a bunch of ******* appear in the password entry field in the locked screen on the ubuntu client.  When the client was subsequently unlocked, the window that had focus was a terminal window and a bunch of line feeds caused the previous content in the terminal to be scrolled up out of view. 

The workaround suggested by klieret points to the issue of how Synergy manages key repeats.

It is my understanding that, on a windows machine (server), when a key is held down, a WM_KEYDOWN event is sent, a wait of 500ms occurs and then repeated WM_KEYDOWN events are sent ("typematic" sequence).  When the key is released, the WM_KEYUP event is sent to terminate the typematic sequence.

I may be guessing at this point but perhaps Synergy server has been designed to somehow manage how many keydown events to send to the client and this mechanism is being broken by some action on the server or by some interruption over the network.  The client is then interpreting this error as a continued repeated key event instead of just resetting its state when the keydown events cease.

**Comment by allanwmacdonald** [comment]
Otherwise, I cannot think of an intended reason the client would generate repeated key events out of the blue and that would be a more dangerous situation (buffer overflow or uninitialized pointer).

**Comment by nbolton** [comment]
This issue has been inactive for a while so I'll close it. Please let me know if this is still an issue and I'll reopen it.

**Comment by denravonska** [comment]
This is still an issue. I'm on 3.0.73.7-rc2. Will try to upgrade to see if it fixes things.

**Comment by nbolton** [comment]
> 3.0.73.7-rc2

Thanks for letting me know. Reopening.

**Comment by denravonska** [comment]
I upgraded to 3.0.80.1-rc3 and haven't seen it since. However, I also disconnected from the company VPN at the same time. Reconnected now to see if I can trigger it again.

**Comment by nbolton** [comment]
> I upgraded to 3.0.80.1-rc3 and haven't seen it since. However, I also disconnected from the company VPN at the same time. Reconnected now to see if I can trigger it again.
> 
> Edit: Yeah, I'm not seeing it at all after the update. Even with the VPN running.

Ok, I'll tentatively close this as I haven't seen it recently either. Not sure what might have fixed it, but I was out of the loop for a bit with bug fixes. Let me know if you see it again in latest and I'll reopen.
