### ISSUE TITLE
Three finger tap is broken on Mac server

### ISSUE THREAD

**Issue by cnf** [symless/synergy#4243]
Mac OS X 10.10

While synergy 1.6.1 is running, even if no clients are connected, three finger tap doesn't work anymore.

Quitting synergy restores the functionality.

**Comment by linickx** [comment]
+1 confirmed. [3 finger tap](http://www.macobserver.com/tmo/article/os-x-the-three-finger-tap-opening-the-dictionary) stops working whilst synergy is running on both client & server. Quitting synergy returns functionality.

Notes: 

1. 2 finger [gestures](http://support.apple.com/en-us/ht4721) work fine on the server trackpad
2. Other 3 finger gestures on the server appear to be broken (3 finger swipe)
3. This issue is *different* to #2905

**Comment by nbolton** [comment]
Duplicates #2905
