### ISSUE TITLE
Missing support for Visual Studio 12

### ISSUE THREAD

**Issue by yulin0629** [symless/synergy#4246]
CMake command: cmake -G "Visual Studio 10" ..
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:39 (project):
  No CMAKE_C_COMPILER could be found.

I have visual studio 2013 community in my windows 7 64bit.

**Comment by JoshMcCullough** [comment]
CMake was hanging for me at `Check for working C compiler using: Visual Studio 10 2010` so I modified the file as suggested by @tumpio to:

	win32_generators = {
		1 : Generator('Visual Studio 12'),
		2 : Generator('Visual Studio 12 Win64'),
		3 : Generator('Visual Studio 11'),
		4 : Generator('Visual Studio 11 Win64'),
		5 : Generator('Visual Studio 10'),
		6 : Generator('Visual Studio 10 Win64'),
		7 : Generator('Visual Studio 10'),
		8 : Generator('Visual Studio 10 Win64'),
		9 : Generator('Visual Studio 9 2008'),
		10: Generator('Visual Studio 9 2008 Win64'),
		11: Generator('Visual Studio 8 2005'),
		12: Generator('Visual Studio 8 2005 Win64')

**Comment by imasonaz** [comment]
Just a suggestion, the if statements can be changed to:
`if generator.startswith('Visual Studio 1'):`
since all will be >Visual Studio 9, confirmed to work with VS12 x64. Also, would it be better to leave option 1 as 2008 to keep with minimum requirements from the wiki?

**Comment by imasonaz** [comment]
Also a note, when using VS2012 / 12.0, the C++ library has some changes that will throw around 100 of these:
`fatal error C1189: #error :  The C++ Standard Library forbids macroizing keywords. Enable warning C4005 to find the forbidden macro.`
The fix is adding `#define _ALLOW_KEYWORD_MACROS 1` to C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xkeycheck.h after line 5.
It seems that the build compiler doesn't check for this.... It may not have been used in previous versions?

**Comment by froghouse** [comment]
The errors are due to the "work around for statement scoping bug" in common/common.h and that is where the fix should be applied. The following warnings aren't "boneheads" or "overly aggressive", they're telling you that you're breaking the C++ language standard.

**Comment by nlyan** [comment]
Made redundant by #4978
