### ISSUE TITLE
Fullscreen apps don't stay on screen when moving mouse to client

### ISSUE THREAD

**Issue by payne8** [symless/synergy#4468]
I am running Windows 8.1 as the server and both Windows 8.1 and Mac OS X Yosemite as clients. All of them are running 1.6.3 with the Windows Focus fix. When I move the cursor to any of my client machines the full screen app is minimized and I can only see the desktop. This only seems to happen to the server.

**Comment by dubuaych** [comment]
I'm not able to test this since I am not running a Win 8.1 server, but the focus fix (for me at least) was only necessary on the Win 8.1 client. I did not change any server binary. Maybe the fix needs to be isolated to the client. From what I recall of the code this may require some refactoring. Of course without proper testing this is all speculation on my part, but I just thought I would throw it out there.

**Comment by XinyuHou** [comment]
scrolllock can limit cursor to current screen
