### ISSUE TITLE
Synergy in elevated mode still disconnecting upon UAC popup

### ISSUE THREAD

**Issue by xorinzor** [symless/synergy#4683]
When running both the server and the client (version 1.7.2) in elevated mode, whenever either gets a UAC message it will cause a disconnect.

Nothing to see in the log screen except for the regular disconnect message.

Running a fresh windows 10 build 10074 x64 install on both the client and the server.

**Comment by IanSmithers** [comment]
I just came here to report this. I am running Windows 8.1 x64 and Windows 7 Ult x64 with Synergy clean install 1.7.3

**Comment by IanSmithers** [comment]
I just came here to report this. I am running Windows 8.1 x64 and Windows 7 Ult x64 with Synergy clean install 1.7.3

**Comment by speaker** [comment]
Unfortunately this functionality is working as designed. The problem comes down to what's happening on a server and client when the UAC window pops up. On a windows machine, the UAC window pops up in a new desktop (not the one synergy was in) that requires special privileges to operate. So on the server the KB and mouse still work because synergy is effectively turned off for the duration. On the client, it's more problematic, because the new desktop doesn't contain a working synergy client that has the privileges to operate. In order to allow interaction on the new desktop, the old client needs to disconnect so a new one with the necessary privileges can interact with the UAC window. Once this is done, the new desktop that contained the UAC window goes away, and the old client needs to connect again. 

There might be ways to make Synergy a bit smarter about when to disconnect (server vs, client for example), however, we've tried having synergy run with privileges in the past with very limited success.

@XinyuHou , any thoughts on this?

**Comment by xorinzor** [comment]
@speaker thanks for clarifying, I did not know that yet. I knew UAC was running in a sandboxed environment, but not a new desktop, which then makes sense as to why it doesn't work.

I'm wondering if there are any workarounds for this

**Comment by dakotak** [comment]
I have this issue with my setup (ubuntu server, windows 7 client), I know that some software has found ways around this. I don't believe this was an issue using inputdirector (windows only). Perhaps there is a way to change the timeout for the reconnect; that would be a good workaround for now.

**Comment by ktiedt** [comment]
Came here looking for a better solution to this... currently I just have to open the server cpanel and "apply" after UAC opens, and again after I tell it "yes" to force reconnects on my Win 10 box... Hope that helps someone else.

**Comment by dpolivy** [comment]
Is this a change in Windows? This used to work fine for me with Synergy 1.4.x on Windows 7, but I've just updated to Windows 10 (server & client), and also re-built Synergy based on the latest code, and now am having issues with UAC.

**Comment by dpolivy** [comment]
OK, I realized that I had previously applied the fix in #3241 to my own compiled copy, and run the client in elevated mode. That's why it worked for me in 1.4.x. I just applied the updated diff in (https://github.com/synergy/synergy/issues/3241#issuecomment-161138349) to the 1.8.1 code, and now it works as expected -- no more disconnects for UAC prompts.

**Comment by ktiedt** [comment]
Does this imply there is a patch that isnt pushed in the official builds that can be applied to avoid this or that we should just run Synergy in elevated status to avoid this?

**Comment by dpolivy** [comment]
@ktiedt You would need to apply the diff in my linked comment, AND run in elevated mode, to address this. Hopefully one of the Synergy devs will see either of these threads and pull the fix in.

**Comment by eweezy** [comment]
@dpolivy How would one go about implementing that? I have enabled elevated mode but I still get disconnects when a UAC popup occurs on my Windows client

**Comment by dpolivy** [comment]
@eweezy You would need to fork the repo, apply the patch in the other issue, and rebuild the binaries/installer yourself. I'll look into providing a PR for this, to at least increase the chances of it getting pulled in sooner.

**Comment by eweezy** [comment]
Thanks so much for the quick reply, and I was afraid you were going to say something like that. I just emailed support about this issue and referenced your patch on github, hopefully they review it and get it touch with you or just implement it. Thanks again and have a great day.

**Comment by dpolivy** [comment]
@eweezy No problem. It's not really trivial to build (at least on Windows) and requires a bunch of really old dependencies at the moment. I just submitted a pull request with the fix, so it's just a simple button click for the Synergy devs to pull it in if they choose. I'm sure they'll post here with any updates.

**Comment by nyetwurk** [comment]
I think this will also fix the issues i've been struggling with in #5041 related to desktop switching, screensavers, and elevation.

**Comment by XinyuHou** [comment]
Can someone test this nightly?
http://synergy-project.org/nightly?filter=synergy-pr5139-fix-redundant-restart-for-elevation-beta-06c853a

**Comment by XinyuHou** [comment]
Duplicate to #3241
