### ISSUE TITLE
Incompatibility with Adobe Photoshop CC

### ISSUE THREAD

**Issue by hmandal** [symless/synergy#5219]
- could not zoom by Alt + Mousewheel
- could not resize or scale using Move tool
- the problem was solved the moment I stopped the server.

There might be more issues, these are the ones I discovered.
I'm using **v1.7.6** of Synergy on Windows 8.1 with 4GB RAM and no other monitor sharing application installed.
I'm was Photoshopping on pc configured as a **server**.
Client was't connected at that time and synergy was running on server.

**Comment by XinyuHou** [comment]
This might be related to #4508

**Comment by DavidST44** [comment]
The only way I've gotten Synergy to work with Photoshop CC was to turn off Elevated mode, however since I updated to Synergy 1.7.6 i've been getting intermittent issues with Photoshop sometimes working sometimes not before on 1.7.5 with elevated mode off it was fine every time.

My issues with Elevated mode on in Photoshop CC were. Using the pen marker trying to click and drag wouldn't work it would only react as if i single clicked and a section so instead of painting lines it'd leave dots. The marque tool to select areas to edit doesn't work at all you click and drag and nothing happens.

**Comment by XinyuHou** [comment]
@DavidST44 
Thanks for the information. Could you move your comment into issue #4508.

I will mark this as closed as it's duplicated to #4508
