### ISSUE TITLE
One mouse click, two separate events

### ISSUE THREAD

**Issue by specialorange** [symless/synergy#5302]
Two laptops (both running same OSX). I want to click one thing (it can be a mouse button, or it can be a key, It doesn't matter), and have both computers recognize it. This would mean (if it was the keyboard example) if they both had a text editor up, and I hit 'a', then an 'a' would appear on both computers screens. If it was a mouse click, they both would at least register the click (doesn't have to mirror the mouse, just the click event).

I am trying to advance two separate presentations at the same time (a master and an accessory slide) going to two different video outputs, but they are for the same presentation. Basically I want to talk about an idea on the left, and show a picture on the right screen, but only click/press once and have both advance.

**Comment by legonigel** [comment]
@specialorange This is not an issue with Synergy. Synergy does not support this feature, and will not add it anytime soon. This is called multiboxing and you can find more about it elsewhere on the internet. Please close this issue.

**Comment by specialorange** [comment]
@legonigel 
Per the email I sent to support, they requested I put this here.

`Hello Chris,
Unfortunately, Synergy does not currently support this feature. However, you can request this feature at: https://github.com/symless/synergy/issues. `

I am unsure of who administers this repo, but it would appear that part of the workflow is to allow GitHub to manage features.  I am not able to change labels....

**Comment by legonigel** [comment]
@specialorange Sorry I misinterpreted your post. It sounded to me like a help desk request, rather than a feature request. Also such a feature has been suggested in #4180. If #4180 matches your feature request, close this issue. If #4180 doesn't match your feature request, I recommend the following to help keep the issues list clean and easy to use:

- Close this issue, because it is now bloated with off-topic discussion
- Open another issue. Give it a more descriptive title, maybe something like: Sending to multiple clients simultaneously 
- In the body of the new issue give a description of the feature alone, no specifics about your scenario are necessary. Explain how the feature should work.

As for labels on the issue, you cannot assign them. They will get assigned when the primary developers get to the issue. Do note that a feature such as this will likely not get implemented any time soon, my best guess would be that it will take a few years before anyone gets to this and therefore I still recommend looking for other solutions.

**Comment by XinyuHou** [comment]
Duplicates to #4180
