### ISSUE TITLE
Spacebar not mapping correctly on Mac

### ISSUE THREAD

**Issue by MisterDenis** [symless/synergy#5337]
When using Synergy (1.7.6) on a Mac server and client, the spacebar input on the server translates to a "/" on the client. No other keys mismatch this way, and the original "/" key also produces the proper character. 

This has been persistent in the past several stable versions.

I have attempted to change the input type to a standard US keyboard - as I use CSA - but I then get whichever character is at the uppermost left of the keyboard. In other words, the mapping only changes the resulting character, not the misbehaviour.

**Comment by clnhs** [comment]
This exact problem with my Windows (7/8/8.1/10 with the Standard Canadian Multilingual layout) server and MacBook Pro (Mac OS 10.7/10.8/10.9/10.10/10.11 with the CSA layout) has been preventing me to use Synergy since I first discovered it. My guess is that it's related to #2765 (then, probably #5015) and #4280. Currently using the latest nightly (2ed3d26).

I've been unsuccessfully trying to change this behavior using Karabiner, but its EventViewer reads code 0xa, identifying with character "/" and KeyCode::DANISH_DOLLAR for both the upper-left key (the tilde key, I guess, for an American keyboard) and the space bar.

And yet, the thing I'd expect the most to fail, namely, the accent keys (é, à, è, and ù) as well as the modifier key (for ^, to type êâû and others) work perfectly well.

**Comment by XinyuHou** [comment]
Duplicates to https://github.com/symless/synergy/issues/2765
