### ISSUE TITLE
Error Compiling on Raspbian (Jessie)

### ISSUE THREAD

**Issue by mahoromax** [symless/synergy#5591]
I followed the Wiki trying to compile synergy.
- installing the dependencies worked fine
- in the configure part I got these errors/warnings:
`-- Looking for XRRNotifyEvent - not found
[...]
Error: Could not get revision, git error: 128`
- In the build part, it works unitl 100% but finishes with:
`make: *** Keine Targets angegeben und keine »make«-Steuerdatei gefunden.  Schluss.
make: Leaving directory '/home/pi/Downloads/synergy-master/src/gui'
Going back to: /home/pi/Downloads/synergy-master
Error: make -w failed with error: 512`

I tried with the SourceCode vom symless.com and 'master' from github. No difference to be detected.
I also tried the conf command with -g1 and -g2, no difference.

**Comment by nlyan** [comment]
We have Raspbian builds on our nightly page at http://symless.com/nightly so the build is working. We will be releasing official builds for Raspberry Pi, probably for v1.8.4.

**Comment by mahoromax** [comment]
Well, I didn't search there.  My system is almost a fresh install, so I wonder where the errors come from.
I am satisfied with finding a working nightly build, but maybe the error points to something. But well. apparently: case closed.

**Comment by nlyan** [comment]
@mahoromax There are a handful of packages that need to be installed to compile Synergy on Raspberry Pi but the build process is essentially the same as for x86 Linux. The documentation for all platforms needs updating, but tbh it's just not a priority right now because we plan on changing the build requirements substantially in 1.9.x

Our nightly packages are for Raspberry Pi 3, but we haven't officially sanctified them yet

**Comment by mahoromax** [comment]
Yes, the nightly build (even master stable, that sounds almost as good as a official rls) works like a charm.
PS: I think the doc about the startup might need workover too, but one can find a solution somewhere else.
