### ISSUE TITLE
Installing 1.8.4 loses all previous settings (Windows and Mac)

### ISSUE THREAD

**Issue by ktiedt** [symless/synergy#5685]
### Operating Systems ###

Server: Mac OS 10.11
Client: Win 10

### Synergy Version ###

1.8.4

### Steps to reproduce bug ###

**READ ME, DELETE ME**: Try to be succinct. If your bug is intermittent, try and describe what you're doing when it happens most.

1. Upgrade to 1.8.4
2. Client now things its a server, server now has no clients configured and all hot keys are missing.

**Comment by pvannuff** [comment]
I seem to have a very similar issue on mac with version 1.8.3. I configured that machine as the server and I use an old style configuration file.

I set up my mac user account to start synergy automatically in the background, but since I upgraded to version  1.8.3 the GUI always is reset to the 'configure interactively' setting. Even the path to my configuration file is always reset to a default.
So on each boot I need to remember to correct these settings.

The same version configured as the client on my windows computer does remember that it's set up as the client, including the server IP (hostname).

Perhaps something wrong with how synergy handles the storage of user-configuration on mac?

**Comment by nlyan** [comment]
This was a bit of a gaff, it should only happen on macOS though since on Windows everything is still in the same place in the registry

**Comment by pvannuff** [comment]
Any idea in which upcoming version this bug will be fixed? :-)

**Comment by nlyan** [comment]
Fixing it will require checking both the old and new locations for settings, and unfortunately, now users have likely already installed 1.8.4, we'd have the same problem going back. It's not a priority right now to fix this one time inconvenience when there are so many other active issues. 

There won't be a need to reconfigure again when going to v1.8.5 and up.

**Comment by pvannuff** [comment]
Ok, thanks a lot for the info!
