### ISSUE TITLE
Suggestion: keyboard approach for switching screen?

### ISSUE THREAD

**Issue by guanpu** [symless/synergy#5711]
Could you add a keyboard approach for switching screen? Either a build-in hotkey or user-defined hotkey would be Okey. The basic idea is **when some hotkey is hit, the active screen will turn to 'next'**(if there are two screens, just switch between server & client, but if there are more clients, maybe we want to mark clients with numbers to achieve this). 
I'm a keyboard man, and don't prefer to use mouse. I believe this feature will make this product even better...

**Comment by auralarch** [comment]
That is already possible and fully configurable/customizable although no default hotkeys have been designated.  You can set it up through the GUI or by editing the configuration file manually.
You have to do the initial setting up of your server with the clients, etc.

There two basic methods for switching between screens (computers):
1. switch in a directions (switch to the screen below or to the right, etc.)
2. switch directly to a particular screen by name

To do this:
Open the server configuration window and click on the middle tab.
Create a new hotkey (which will show up in the left column), then select it and create a new action.  All the options will be in the popup window that appears.

If you want to set it up so that with one hotkey you can endlessly switch to the 'next' screen you must manually edit the text-based config file.
In the 'links' section you must add lines so that the screens at either end of the row/column refer back to the first one- so they are 'wrapped'.
Once you take a look at the config file it should be clear how to accomplish that.

Hope that helps!

BTW, I'm experiencing difficulties getting it to work properly right now (with an OSX server)- not sure why but I'm researching now...

**Comment by guanpu** [comment]
@auralarch , Thank you for your detailed reply. It really helps.
I've tried successfully according to your instruction. So to toggle between two screens(Computers) with unique hotkey, we can set the links to left and to right pointing to the same computer in the configure file.
My Environment: Oracle Linux 6 + Windows 7 with synergy version 1.8.4-stable-1796150.
Thanks again.

**Comment by nlyan** [comment]
Closed. Functionality already available. Please create a separate issue if you have problems
