### ISSUE TITLE
Benefit of payed version?

### ISSUE THREAD

**Issue by clankill3r** [symless/synergy#5766]
I was wondering, what is the benefit of the payed version?
I landed on https://symless.com today not knowing you could also get it for free.
Don't get me wrong, I love to pay for the support cause I think the idea behind it it really great.
But so far, i encountered 2 bugs already that forced me to restart the client. Looking at the issues page, there are issues from 2014 labeled priority urgent.
I think this makes the 19$ price kind of steep for the quality.

**Comment by polarathene** [comment]
The best you can do is report those bugs, perhaps let them know you're a paid user if that might influence priority of bug fixes. The more that voice up about it, within reason the sooner you'd likely see a fix. I don't know what their team size is or if they're full time, the product has been solid quality for me so far and definitely worth what I paid(around $10 I think, the higher price you quote might be a premium version with some other features). **EDIT** Just took a look, I either got it on special or they've increased the prices since, $10 is an easy buy for me, I can understand $20 being a bit much before you try.

I believe you can get it free, you have to compile it yourself or be provided a compiled version(third party site or package manager). I'm not sure if the free version is easily available free online compiled, one of the benefits of paying was you get a download link direct from symless, other sources may not release updates as fast, another concern might be malware from a third party source(I'd doubt it with package managers and linux, but not hard to believe a scammer targeting windows customers who tend to be less tech savvy). I use my package manager on my Linux host and the windows version provided by symless via paid license as speed was important to me and I'm happy to support these guys for what they were asking.

I believe paid versions were only introduced recently(this year?) and development pace is picking up, financial support from users will help to ensure the quality improves... that does sort of require paying customers to effectively do that, else you have a chicken/egg scenario.

I use synergy very frequently and it saves me hassle of USB redirection, multiple mouse/keyboard(easily cost alone), some users mention buying USB expansion cards(covers premium at least once almost twice or more for a decent card). My use case is one computer with multiple hybrid VMs, synergy has been a fantastic solution. If they don't already, providing a free trial version or support nag(like sublime?) and making it clear that's available might be nice. It's a lifetime license with free updates, premium even gets you support priority that may help resolve your problem bugs you encounter or at least get them more attention for devs.

**Comment by nlyan** [comment]
A lot of these bugs predate for the formation of the company, 3 years ago, prior to which the project had been abandoned for a good 8 years.

It is only this year that we've got a support engineer, a web developer, and 2 full time developers ( me and @XinyuHou ). For a one-off modest fee of $20 you're getting a commitment from us to work on Synergy and, while we're aware there are still far too many core bugs, I can assure you that things are moving at a pace in at Symless HQ and you will see change throughout 2017

**Comment by XinyuHou** [comment]
Close as this is not an product issue
