### ISSUE TITLE
Error building v1.9.0

### ISSUE THREAD

**Issue by NathanW42** [symless/synergy#5794]
### Operating System ###

Windows 10

### Synergy Version ###

1.9.0

### Other info ###

- When the command "hm configure -g1" is run I get the error "Failed to access CRT version.
WARNING: Unable to generate output for: C:/Users/ncwil/Documents/git/synergy/src/gui/Makefile.Release [TEMPLATE app]"

- Link to the full cmd log
https://gist.github.com/NathanW42/378b117a1dea36d435d912e3492ce6a0

**Comment by yupi2** [comment]
According to [this](https://github.com/wweiradio/qt-everywhere-opensource/blob/master/qtbase/qmake/generators/win32/msvc_nmake.cpp#L183) Qt can't find the `UCRTVersion` environment variable. I don't know the solution for this so you could try starting a `VS2015 x86 Native Tools Command Prompt` (since you're build building for x32 Windows (-g1)) and then trying `hm configure -g1` again.

**Comment by NathanW42** [comment]
Thank you. Running through the VS2015 command prompt worked.
