### ISSUE TITLE
Recognize individual screen size

### ISSUE THREAD

**Issue by byWulf** [symless/synergy#5902]
Synergy is trading multiple monitors on the client as one big monitor as far as I read. That leads to a problem, when the resolutions are different, what happens often with a laptop + external monitor.

![clientresolutions](https://cloud.githubusercontent.com/assets/135651/23789682/33788a96-057c-11e7-8082-19b22aa59b82.png)

When drawing a rectangle around the client monitors, there is an area with no monitor. When moving the mouse to this area, synergy virtually moves the mouse into it. So when you think, you are at the bottom of your monitor, and you want to move the mouse up again, it don't instantly moves up, but first moves out of the invisible area and starts moving up on the real monitor after that.

![logmovement](https://cloud.githubusercontent.com/assets/135651/23789683/3378f26a-057c-11e7-9d6a-9041ef25806f.png)

It will get uncomfortable when you want to press on a programm in your taskbar. So you move your mouse down much, because the bottom border of the monitor should stop your mouse movement, click on the programm you want to focus, and then move the mouse up again. You will have to move the mouse up more than expecting, because you first have to move it out of the invisible area.

Also another side effect is moving the mouse from the bigger monitor into the invisible area of the smaller monitor, it works. You can move your mouse as much as you want in this invisible area.

![expection](https://cloud.githubusercontent.com/assets/135651/23789684/33796a4c-057c-11e7-8d3c-8b8512bb0975.png)
(Red: movement of the mouse, Green: Expected behaviour)

And finally another side effect: Windows 10 introduced snapping corners for easier closing windows, hitting start button or going to desktop. These snapping corners work well on the server, but won't work on the client. Even on the upper aligned borders you can't get your mouse to hold on the Close-Window-Button.

### Operating Systems ###

Server: Windows 10
Client: Windows 10

### Synergy Version ###

1.8.8-stable-c30301e (updated half an hour ago)

### Steps to reproduce bug ###

Entering the invisible area from the upper side:
1. Configure your client with two monitors of different resolutions. Place the smaller monitor to the left and align the upper borders.
2. Configure your server so the client is left of the server.
3. Move your mouse to the left client monitor (stay vertically in the middle).
4. Move your mouse to the bottom and move it down a bit more.
5. Move your mouse up again. **The bug occurs.** The mouse will need a while until it really starts moving up.

Entering the invisible area from another monitor:
1. Configure your client with two monitors of different resolutions. Place the smaller monitor to the left and align the upper borders.
2. Configure your server so the client is left of the server.
3. Move your mouse to the right client monitor.
4. Move your mouse to the bottom.
5. Move your mouse to the left into the left client monitor. **The bug occurs.** You shouldn't be able to get to the left client monitor.
6. Move your mouse up. **The bug occurs.** The mouse will need a while until it really starts moving up.

### Other info ###

* When did the problem start to occur? Since I reinstalled synergy 1 1/2 years ago.
* Is there a way to work around it? Moving your mouse really carefully. Not really a work around.
* Does this bug prevent you from using Synergy entirely? No

Some cherrypicked log informations which should describe the bug:
```
[2017-03-10T10:01:54] DEBUG: received client "DESKTOP-IV581NQ" info shape=0,0 3520x1080 at 0,0 (no, my client is not a regular rectangle)
[...]
[2017-03-10T10:01:59] INFO: switch from "Wulf-PC" to "DESKTOP-IV581NQ" at 3519,836
[...]
[2017-03-10T10:03:11] DEBUG2: onMouseMoveSecondary +1,+0
[2017-03-10T10:03:11] DEBUG2: move on DESKTOP-IV581NQ to 796,899 (thats ok, but should be the limit)
[2017-03-10T10:03:11] DEBUG2: send mouse move to "DESKTOP-IV581NQ" 796,899
[...]
[2017-03-10T10:03:11] DEBUG2: onMouseMoveSecondary +0,+1
[2017-03-10T10:03:11] DEBUG2: move on DESKTOP-IV581NQ to 796,901 (should not be possible)
[2017-03-10T10:03:11] DEBUG2: send mouse move to "DESKTOP-IV581NQ" 796,901
[...]
[2017-03-10T10:03:22] DEBUG2: onMouseMoveSecondary +0,+1
[2017-03-10T10:03:22] DEBUG2: move on DESKTOP-IV581NQ to 804,941 (should not be possible)
[2017-03-10T10:03:22] DEBUG2: send mouse move to "DESKTOP-IV581NQ" 804,941
```

![synergyconfig_1](https://cloud.githubusercontent.com/assets/135651/23789686/337d8712-057c-11e7-8a1b-e8b2922a50b9.png)
![synergyconfig_2](https://cloud.githubusercontent.com/assets/135651/23789685/337a9a0c-057c-11e7-8407-2d976dc56fd1.png)

**Comment by devdoomari** [comment]
synergy displays configuration UI should be re-done to fix this issue...
to account for multiple monitors, how about showing 'groups' of monitors for a host?
(which would be similar to windows 10 multi-monitor configuration UI, with 'colors' to group by hosts)

**Comment by ColinCreamer** [comment]
I agree @devdoomar completely with having 'groups' of monitors. I`ve been wanting proper multi monitor support implemented for years. I made the same sort of request in 2015 with issue #4795, though it got closed nearly immediately due to similarities to other issues. Synergy really does need to rework the monitor UI so that it recognizes and displays the multi monitor layout of all computers connected, server and client. This way each computers monitor layout group, reflects the actual shape of all monitors on that computer, and, so each group can be positioned to fit together like puzzle pieces.
![multimonitory layout support](https://cloud.githubusercontent.com/assets/2904388/24076871/b9678d2c-0c12-11e7-9cab-32affc993c5e.png)

**Comment by devdoomari** [comment]
@ColinCreamer nice drawing : )

**Comment by 1j01** [comment]
A couple years ago I started working on a synergy client that was going to support this. I was about to implement snapping but I found a jQuery UI function that [did](https://github.com/1j01/nw-synergy/commit/0942fa7f8baeb5870798b1fa41d5fab42e5d7170) something like 90% of what I needed for 10% of the [work](https://github.com/1j01/nw-synergy/commit/6d0124d2acc87d901514f054d6e3a7c419bd0e40). You can play around with the start of the interface [here](http://1j01.github.io/nw-synergy/).
[![nw-synergy](https://cloud.githubusercontent.com/assets/3630663/24077804/9df0125e-0c2f-11e7-9b9b-6aa43d24df01.png)](http://1j01.github.io/nw-synergy/)
It can kinda detect one monitor from the web page, but it does multi-monitor detection in the NW.js app. ([Here's the repo.](https://github.com/1j01/nw-synergy))
[![nw-synergy 4](https://cloud.githubusercontent.com/assets/3630663/24078096/9948f130-0c39-11e7-93f0-9553a874834e.png)](https://github.com/1j01/nw-synergy)
I think it shouldn't be too hard to implement dragging and snapping conjoint monitors. In fact it could work to just move connected monitors with the dragged monitor, which would technically give you more control than if it handled snapping of the whole shape at once.

**Comment by yupi2** [comment]
@1j01 Pretty nice. Implementing the current Synergy GUI program in HTML/JS/CSS and serving it from a local webserver binary would be great for removing the Qt (C++ GUI library) dependency in the project too.

**Comment by ColinCreamer** [comment]
@1j01 Great demo. Very cool.
That would be excellent if synergy implemented snapping and monitor placement such as yours.
On a side note: I frayed away form requesting manipulation of every monitor independently, since I didn't want to ask for too much. Independent monitor manipulation would require synergy re-configuring the operating systems monitor layout.  Also if we have full individual monitor placement control, for multiple monitors from multiple different machines, the snapping logic would have to be smart enough to prevent invalid monitor arrangements. IE. every monitor from the same computer HAS to be touching another monitor from the same computer Figured best just leaving the local computers monitor arrangement  to be done using OSs provided GUI, then in synergy, only arranging each computers cluster of monitors as a whole. For the first version anyways.

**Comment by 1j01** [comment]
@ColinCreamer Thanks, and yeah, that's what I was thinking - keep it simple for now.
I've just done a basic (hacky) implementation of multi-monitor dragging as a proof of concept. Aside from silly issues like it snapping to other monitors of the same computer where they were at the start of the drag, and pixel-accuracy problems because I haven't set up a proper data model... it works, but snapping based on the dragged monitor isn't enough; it definitely needs to take into account the whole shape when snapping.

![nw-synergy 7](https://cloud.githubusercontent.com/assets/3630663/24078944/165a2e1a-0c52-11e7-81e3-38409b25be5b.png)

So, I could rewrite this with React, do it properly and try to implement (convex) shape snapping.

**Comment by wagle** [comment]
I very much need individual monitor support.  What would be the right way for me to help with that?

Detail:  Right now I have 2 computers.  Computer 1 has 3 monitors, different sizes.  Computer 2 has 2 monitors, the same size.  They are roughly physically arranged as:

1 2 2
1 1 

Thanks!

**Comment by nbolton** [comment]
Duplicates https://github.com/symless/synergy/issues/4173

**Comment by molecular** [comment]
anyone else thinking about Tetris?

**Comment by nbolton** [comment]
Duplicates #4173

**Comment by LeadManPL** [comment]
@nbolton according to GitHub documentation:
"For a "marked as duplicate" **timeline event to appear**  [...] type **"Duplicate of"** followed by the issue or pull request number"

"Duplicate of" not "Duplicates"

**Comment by nbolton** [comment]
Duplicate of #4173

**Comment by nbolton** [comment]
@LeadManPL Very cool! Thanks for that.
