### ISSUE TITLE
Website Password Reset is Broken

### ISSUE THREAD

**Issue by devjj** [symless/synergy#5918]
### Operating Systems ###

Client: Safari on macOS Sierra

### Synergy Version ###

N/A

### Steps to reproduce bug ###

1. Go to Account page on Synergy website
2. Attempt to reset password by submitting email
3. Bug occurs.

### Other info ###

* It is REALLY crappy that I had to submit this here because your website doesn't have an obvious way to reach out to you. We paid money for your product!

**Comment by qbuchanan** [comment]
I second the issue.  In fact any part of the website where you need to log in seems to be broken, including all the help desk pieces as well.  I finally came here to post he issue after trying to contact symless via irc (no one there) and email which returns an error: No valid recipient

please let us know when the website gets up and running again and I would highly recommend making it easier to contact symless by adding a help or webmaster emails.  As a last resort I may have to join twitter <shudder> to get a message to you

**Comment by qbuchanan** [comment]
the email address I used was  issues@symless.com.

**Comment by XinyuHou** [comment]
@DanSorahan

**Comment by DanSorahan** [comment]
Hey Joseph,

As you may have seen in @nbolton's recent email, we've made some major improvements to our security system and due to this, all passwords must be reset.

Yesterday from around 6PM GMT, our servers were affected by the [libc6_2.19-0ubuntu6.10](https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1674733) issue. This resulted in sendmail being unable to spool to our smtp server meaning that password reset emails weren't being sent out. Unfortunately, due to a misconfiguration in an old monitoring policy, we weren't alerted to the problem for a number of hours. We've taken steps to improve response time to issues in the future, and to ensure this problem doesn't happen again.

In regards to email contact, the correct email address is `login-issues@symless.com` as noted on the login failure error message.
