### ISSUE TITLE
Using remote control tools to assist someone with synergy gets mouse stuck off window

### ISSUE THREAD

**Issue by odgeza** [symless/synergy#5930]
### Operating Systems ###

Server: Any windows (but specifically Windows 10.1607 Build 14393.953)
Client: Any windows (but specifically Windows 10.1607 Build 14393.953)

### Synergy Version ###

1.8.2-stable-36cd521

### Steps to reproduce bug ###

1. Teamviewer or VNC or any remote tool to a PC running synergy
2. Move the mouse to near the region of the edge to jump over
3. The remote user, can no longer move the mouse and there is no way for them to move it back
4. The local user has to move the mouse back for the user

### Other info ###

I know this seems like its not your problem, but its really annoying in a company where team members assist eachother all day long, whenever you get the mouse close to the edge, you have to keep asking the other user to move it back. Maybe there is a smart way to deal with this.

**Comment by XinyuHou** [comment]
@odgeza 
We do have a plan to develop another product called TeamScreen which would help a team to cooperate with each other by remoting control others' machines.

For Synergy itself, there is really not much we can do. Because both Synergy and remote tool requires low level input control which would cause conflict.

The best I can suggest is to subscribe to Symless mailing list so you will get updated when the TeamScreen prototype is available.
