### ISSUE TITLE
OpenSSL and failed to connect to server timed out issue 

### ISSUE THREAD

**Issue by GiraldoMedia** [symless/synergy#5952]
### Other info ###

* When did the problem start to occur? When I connect to my vpn
* Is there a way to work around it? No
* Does this bug prevent you from using Synergy entirely? Yes

When i start up the 2 windows 7 computers, synergy works on the network fine. as soon as the laptop connectsa to the vpn synergy gives me an openssl and failed to connect to server timed out issue.

**Comment by deckar01** [comment]
I suspect the issue is your firewall.

```
Server -> Local Network -> Client
```

This works, because both devices are behind the same firewall.

```
Server -> VPN -> Internet -X Firewall -> Local Network -> Client
```

This doesn't work, because your firewall does not have any rules that tells it to trust your VPN server. Data transmitted over a VPN usually has high latency which will result in a choppy / slow mousing experience.

The best solution is likely to instruct your VPN route the traffic on Synergy's port to the local network instead of routing it to a remote server. The feature is called [Split Tunneling](https://en.wikipedia.org/wiki/Split_tunneling), but not all VPN clients offer this kind of advanced configuration.

**Comment by XinyuHou** [comment]
This looks like a support ticket. Please use our forum and mailing list for community support. Thanks

https://symless.com/forum
synergy-users@googlegroups.com
