### ISSUE TITLE
[Suggestion] Option to lock cursor on screen when clicking

### ISSUE THREAD

**Issue by LasaFawkes** [symless/synergy#5993]
Hey! It would be nice having this as an option so you don't jump from screen to screen when scrolling down a webpage, for instance. I tend to move my mouse at a bit of an angle when scrolling and the mouse ends up on another screen, it's annoying. Thank you in advance!

**Comment by DananFlander** [comment]
I tried this using the hotkeys functionality by attaching the lockCursorToScreen(on) action to the mousebutton1 hotkey being pressed, then attaching the lockCursorToScreen(off) action to the mousebutton1 hotkey being released. The hotkey pressed action triggers and locks the cursor to the screen, but the hotkey released action does not appear register, so the cursor stays locked upon release of mousebutton1. Here are screenshots of the settings I am describing:

[mousebutton1 press](https://t.gyazo.com/teams/cloud9/37f21168a1c6b2ffe189dd8d496c7452.png)

[mousebutton1 release](https://t.gyazo.com/teams/cloud9/6058c9fa0b8755c1045305c9374382c2.png)

Instead of rigging it this way, allowed a Push-to-Lock option where you set the key would be a more streamlined approach. That convention is used in many applications for Push-to-Talk functionality, so I don't see why it couldn't be useful here.

Anyone have thoughts or feedback on this?

Thanks!

**Comment by XinyuHou** [comment]
@LasaFawkes 
If you disable file drag and drop in settings, this would block switching while you holding down a mouse button.

**Comment by LasaFawkes** [comment]
@XinyuHou 
Easy enough! That's exactly what I was looking for. Thank you!
