### ISSUE TITLE
com.http-synergy-project-org.Synergy.plist grows to 1+ GB in size every couple of days

### ISSUE THREAD

**Issue by MartinRJ** [symless/synergy#6024]
### Operating Systems ###

macOS Sierra 10.12.4

### Synergy Version ###

1.8.8

### Steps to reproduce bug ###

The file com.http-synergy-project-org.Synergy.plist grows to 1+ GB in size on my mew MacBook Pro every couple of days - about once a week, and then the application cannot be started anymore.
I have to delete everything manually.

All related issues I found have been closed, or have to do with other problems.

I own multiple pro-licenses, and the app isn't really useful with this bug not fixed.

And I am a bit annoyed that people keep closing issues with this cause (the insanely large .plist file), but the underlying bug is not fixed yet.

**Comment by aristizabal95** [comment]
Possibly related to #5901. Same behavior, but instead of `com.http-synergy-project-org.Synergy.plist`, it occurs with the file `com.http-symless-com.Synergy.plist`. Could you please check if you have this other file inside your `~/Library/Preferences` folder? and if so, if the serial key is stored in such file?

**Comment by aristizabal95** [comment]
The temporal solution I've found is to have a copy of the original plist files and replace the corrupted ones with this backup. Still, this does not solve the underlying problem, just allows you to get going with synergy fast.

**Comment by nlyan** [comment]
Fixed by 165bfa3dd6ce9a9b695f522fbd6b94b4608fe876 . Will be released in v1.9.0
